USE Clinica;

CREATE TABLE Medico(
Id INT IDENTITY(1,1) PRIMARY KEY,
CRM VARCHAR(15) UNIQUE NOT NULL,
Nome VARCHAR(200) NOT NULL,
DataNascimento DATETIME,
Especialidade VARCHAR(100) NOT NULL,
CPF VARCHAR(15) UNIQUE NOT NULL,
DataAdmissao DATETIME NOT NULL
)